[package]
name = "void-game"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
void-math.workspace = true
void-entity.workspace = true
void-console.workspace = true
void-physics.workspace = true
void-bsp.workspace = true
glam.workspace = true
log.workspace = true
void-map.workspace = true

[dev-dependencies]
void-kv.workspace = true
