[package]
name = "forge"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
kerosene-asset.workspace = true
kerosene-math.workspace = true
kerosene-kv.workspace = true
anyhow.workspace = true
clap.workspace = true
log.workspace = true
env_logger.workspace = true
glam.workspace = true
thiserror.workspace = true
