[package]
name = "kerosene-vfs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Kerosene's virtual filesystem: search paths, .vault archives and project discovery."
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
anyhow.workspace = true
kerosene-kv.workspace = true
thiserror.workspace = true
log.workspace = true
