[package]
name = "void-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
void-engine.workspace = true
void-vfs.workspace = true
void-game.workspace = true
void-console.workspace = true
void-math.workspace = true
anyhow.workspace = true
log.workspace = true
env_logger.workspace = true
clap.workspace = true

[[bin]]
name = "void"
path = "src/main.rs"
