// SPDX-License-Identifier: LGPL-3.0-or-later
//! Reading WAV files.
//!
//! Written out rather than pulled in, because the useful subset is small and
//! a decoder is a place where an unexpected file should produce an error
//! rather than a panic or a very large allocation. Every length in a RIFF file
//! is attacker-controlled in the sense that matters here: content is edited by
//! people and generated by tools, and a truncated file is a normal Tuesday.
//!
//! Handles what an audio tool actually writes: PCM at 8, 16, 24 and 32 bits,
//! and 32-bit float, mono or stereo. Everything is decoded to `f32` in
//! [-1, 1], because the mixer works in floats and converting once at load is
//! cheaper and clearer than converting per sample per frame.

use crate::AudioError;

/// Decoded audio: interleaved samples, one set per frame.
#[derive(Clone, PartialEq, Debug)]
pub struct Sound {
    pub channels: u16,
    pub sample_rate: u32,
    /// Interleaved, `channels` per frame, each in [-1, 1].
    pub samples: Vec<f32>,
}

impl Sound {
    /// How many frames -- samples divided by channels.
    pub fn frames(&self) -> usize {
        if self.channels == 0 { return 0 }
        self.samples.len() / self.channels as usize
    }

    pub fn duration(&self) -> f32 {
        if self.sample_rate == 0 { return 0.0 }
        self.frames() as f32 / self.sample_rate as f32
    }

    pub fn is_empty(&self) -> bool { self.samples.is_empty() }

    /// One channel of a frame, or silence past the end.
    pub fn sample(&self, frame: usize, channel: u16) -> f32 {
        let channel = channel.min(self.channels.saturating_sub(1)) as usize;
        self.samples
            .get(frame * self.channels as usize + channel)
            .copied()
            .unwrap_or(0.0)
    }
}

/// The largest file we will decode, as a guard against a bad length field
/// asking for a terabyte.
const MAX_BYTES: usize = 256 * 1024 * 1024;

const FORMAT_PCM: u16 = 1;
const FORMAT_FLOAT: u16 = 3;
const FORMAT_EXTENSIBLE: u16 = 0xFFFE;

pub fn decode(bytes: &[u8]) -> Result<Sound, AudioError> {
    if bytes.len() > MAX_BYTES {
        return Err(AudioError::Malformed("file is implausibly large".into()));
    }
    if bytes.len() < 12 || &bytes[0..4] != b"RIFF" || &bytes[8..12] != b"WAVE" {
        return Err(AudioError::Malformed("not a RIFF/WAVE file".into()));
    }

    let mut format: Option<Format> = None;
    let mut data: Option<&[u8]> = None;
    let mut at = 12usize;

    while at + 8 <= bytes.len() {
        let id = &bytes[at..at + 4];
        let size = u32::from_le_bytes(bytes[at + 4..at + 8].try_into().expect("4 bytes")) as usize;
        let body_at = at + 8;
        // A truncated final chunk is common enough -- a recording stopped
        // mid-write -- that taking what is there beats refusing the file.
        let end = body_at.saturating_add(size).min(bytes.len());
        let body = &bytes[body_at.min(bytes.len())..end];

        match id {
            b"fmt " => format = Some(parse_format(body)?),
            b"data" => data = Some(body),
            _ => {}
        }

        // Chunks are padded to even lengths.
        at = body_at + size + (size & 1);
        if size == 0 && id != b"data" { break }
    }

    let format = format.ok_or_else(|| AudioError::Malformed("no fmt chunk".into()))?;
    let data = data.ok_or_else(|| AudioError::Malformed("no data chunk".into()))?;

    if format.channels == 0 || format.channels > 2 {
        return Err(AudioError::Unsupported(format!(
            "{} channels; mono and stereo only",
            format.channels
        )));
    }
    if format.sample_rate == 0 {
        return Err(AudioError::Malformed("a sample rate of zero".into()));
    }

    let samples = match (format.tag, format.bits) {
        (FORMAT_PCM, 8) => data.iter().map(|&b| (b as f32 - 128.0) / 128.0).collect(),
        (FORMAT_PCM, 16) => data
            .chunks_exact(2)
            .map(|c| i16::from_le_bytes([c[0], c[1]]) as f32 / 32768.0)
            .collect(),
        (FORMAT_PCM, 24) => data
            .chunks_exact(3)
            .map(|c| {
                // Sign-extend the top byte into a 32-bit value.
                let v = i32::from_le_bytes([0, c[0], c[1], c[2]]);
                v as f32 / 2_147_483_648.0
            })
            .collect(),
        (FORMAT_PCM, 32) => data
            .chunks_exact(4)
            .map(|c| i32::from_le_bytes([c[0], c[1], c[2], c[3]]) as f32 / 2_147_483_648.0)
            .collect(),
        (FORMAT_FLOAT, 32) => data
            .chunks_exact(4)
            .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
            .collect(),
        (tag, bits) => {
            return Err(AudioError::Unsupported(format!(
                "format {tag} at {bits} bits"
            )));
        }
    };

    Ok(Sound { channels: format.channels, sample_rate: format.sample_rate, samples })
}

struct Format {
    tag: u16,
    channels: u16,
    sample_rate: u32,
    bits: u16,
}

fn parse_format(body: &[u8]) -> Result<Format, AudioError> {
    if body.len() < 16 {
        return Err(AudioError::Malformed("fmt chunk is too short".into()));
    }
    let mut tag = u16::from_le_bytes([body[0], body[1]]);
    let channels = u16::from_le_bytes([body[2], body[3]]);
    let sample_rate = u32::from_le_bytes([body[4], body[5], body[6], body[7]]);
    let bits = u16::from_le_bytes([body[14], body[15]]);

    // WAVE_FORMAT_EXTENSIBLE hides the real format in a GUID whose first two
    // bytes are the tag it would otherwise have carried.
    if tag == FORMAT_EXTENSIBLE {
        if body.len() < 26 {
            return Err(AudioError::Malformed("extensible fmt chunk is too short".into()));
        }
        tag = u16::from_le_bytes([body[24], body[25]]);
    }

    Ok(Format { tag, channels, sample_rate, bits })
}

#[cfg(test)]
mod tests;
