[package]
name = "kerosene-entity"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
kerosene-math.workspace = true
kerosene-kv.workspace = true
kerosene-bsp.workspace = true
kerosene-console.workspace = true
kerosene-physics.workspace = true
glam.workspace = true
log.workspace = true
anyhow.workspace = true
kerosene-map.workspace = true
thiserror.workspace = true
