[package]
name = "kerosene-asset"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Kerosene's compiled asset formats: textures, materials and models."
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
kerosene-math.workspace = true
kerosene-kv.workspace = true
anyhow.workspace = true
thiserror.workspace = true
glam.workspace = true
bytemuck.workspace = true
log.workspace = true
