[package]
name = "kerosene-bsp"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "The compiled-map format of the Kerosene game engine: BSP tree, visibility, lighting and acoustics."
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
kerosene-math.workspace = true
kerosene-kv.workspace = true
kerosene-vfs.workspace = true
anyhow.workspace = true
thiserror.workspace = true
glam.workspace = true
bytemuck.workspace = true
log.workspace = true
