[package]
name = "kerosene-rigid"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Rigid-body props for the Kerosene game engine."
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
box3d-rust.workspace = true
kerosene-math.workspace = true
glam.workspace = true
