[package]
name = "kerosene-script"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Rhai map scripting for the Kerosene game engine."
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
kerosene-math.workspace = true
rhai.workspace = true
kerosene-platform.workspace = true
log.workspace = true
thiserror.workspace = true
serde_json.workspace = true
