[package]
name = "void-engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
void-math.workspace = true
void-bsp.workspace = true
void-asset.workspace = true
void-vfs.workspace = true
void-console.workspace = true
void-entity.workspace = true
void-physics.workspace = true
void-render.workspace = true
glam.workspace = true
anyhow.workspace = true
log.workspace = true
winit.workspace = true
wgpu.workspace = true
pollster.workspace = true
env_logger.workspace = true
