[package]
name = "void-entity"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
void-math.workspace = true
void-kv.workspace = true
void-bsp.workspace = true
void-console.workspace = true
void-physics.workspace = true
glam.workspace = true
log.workspace = true
anyhow.workspace = true
void-map.workspace = true
thiserror.workspace = true
