[package]
name = "cleave"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
kerosene-math.workspace = true
kerosene-map.workspace = true
kerosene-bsp.workspace = true
kerosene-walk.workspace = true
kerosene-kv.workspace = true
anyhow.workspace = true
clap.workspace = true
log.workspace = true
env_logger.workspace = true
rayon.workspace = true
glam.workspace = true
thiserror.workspace = true

[lib]
name = "cleave"
path = "src/lib.rs"

[[bin]]
name = "cleave"
path = "src/main.rs"
