// SPDX-License-Identifier: LGPL-3.0-or-later
//! The standard developer texture set, generated rather than shipped.
//!
//! Two families, and both earn their place before a single piece of real art
//! exists.
//!
//! **`dev/`** are measurement textures. A grey and orange grid at a known
//! scale, so that a room's size can be read off its walls: at the default
//! texture scale one cell is 16 void units and one tile is 64. Building a
//! level in flat colours means guessing at proportion for as long as it takes
//! to make art, and guessing wrong is expensive to undo.
//!
//! **`tools/`** are the invisible ones -- `nodraw`, `clip`, `trigger`, `hint`,
//! `skip` -- which the compiler already understood and which nothing had ever
//! drawn. A mapper who picked `tools/nodraw` in Chisel got a missing texture.
//! Each is a flat colour with its own name written across it, because a colour
//! alone does not tell `clip` from `playerclip` at a glance.
//!
//! Generated by a tool rather than committed as art, because they are
//! *defined* by numbers -- this grid is 16 units, that colour means "blocks
//! players" -- and a definition that lives in a PNG is one nobody can read.

use crate::font;
use anyhow::{Context, Result};
use std::path::Path;

/// Side length of a `dev/` texture, in texels.
///
/// At the default texture scale of 0.25 world units per texel this covers 64
/// void units, so the 4x4 grid drawn on it reads as 16-unit cells -- the grid
/// size most brushwork is actually done at.
pub const DEV_SIZE: u32 = 256;

/// Side length of a `tools/` texture. Smaller: they carry a word, not detail.
pub const TOOL_SIZE: u32 = 128;

/// World units one `dev/` texture spans at the default scale.
pub const DEV_SPAN: u32 = 64;
/// World units per grid cell on a `dev/` texture.
pub const DEV_CELL: u32 = 16;

type Rgb = [u8; 3];

/// A simple RGB image being drawn into.
pub struct Canvas {
    pub width: u32,
    pub height: u32,
    pub pixels: Vec<u8>,
}

impl Canvas {
    pub fn new(width: u32, height: u32, fill: Rgb) -> Canvas {
        let mut pixels = Vec::with_capacity((width * height * 3) as usize);
        for _ in 0..width * height {
            pixels.extend_from_slice(&fill);
        }
        Canvas { width, height, pixels }
    }

    pub fn set(&mut self, x: i32, y: i32, colour: Rgb) {
        if x < 0 || y < 0 || x >= self.width as i32 || y >= self.height as i32 { return }
        let at = ((y as u32 * self.width + x as u32) * 3) as usize;
        self.pixels[at..at + 3].copy_from_slice(&colour);
    }

    pub fn get(&self, x: i32, y: i32) -> Rgb {
        if x < 0 || y < 0 || x >= self.width as i32 || y >= self.height as i32 { return [0, 0, 0] }
        let at = ((y as u32 * self.width + x as u32) * 3) as usize;
        [self.pixels[at], self.pixels[at + 1], self.pixels[at + 2]]
    }

    /// Blend a colour over what is there.
    pub fn blend(&mut self, x: i32, y: i32, colour: Rgb, alpha: f32) {
        let alpha = alpha.clamp(0.0, 1.0);
        let under = self.get(x, y);
        let mixed = [
            mix(under[0], colour[0], alpha),
            mix(under[1], colour[1], alpha),
            mix(under[2], colour[2], alpha),
        ];
        self.set(x, y, mixed);
    }

    fn rect(&mut self, x0: i32, y0: i32, x1: i32, y1: i32, colour: Rgb) {
        for y in y0..y1 {
            for x in x0..x1 {
                self.set(x, y, colour);
            }
        }
    }

    /// Write text, centred on a point, with a dark outline so it reads on any
    /// background.
    pub fn text(&mut self, text: &str, centre: (i32, i32), scale: usize, colour: Rgb) {
        let w = (font::width(text) * scale) as i32;
        let h = (font::GLYPH_H * scale) as i32;
        let origin = (centre.0 - w / 2, centre.1 - h / 2);

        // The outline first, as a one-pixel halo in every direction.
        for (dx, dy) in [(-1, 0), (1, 0), (0, -1), (0, 1), (-1, -1), (1, -1), (-1, 1), (1, 1)] {
            font::draw(text, (origin.0 + dx, origin.1 + dy), scale, |x, y| {
                self.blend(x, y, [12, 12, 14], 0.75);
            });
        }
        font::draw(text, origin, scale, |x, y| self.set(x, y, colour));
    }

    /// Write a PNG, and say whether the file changed.
    ///
    /// The set is committed to the repository *and* regenerated by the build,
    /// which only works because the generator is deterministic -- so the
    /// interesting question on every run is "did anything move", and a build
    /// that quietly rewrites tracked files without answering it is one nobody
    /// trusts.
    pub fn to_png(&self, path: &Path) -> Result<bool> {
        if let Some(parent) = path.parent() { std::fs::create_dir_all(parent)?; }
        let image = image::RgbImage::from_raw(self.width, self.height, self.pixels.clone())
            .context("canvas dimensions do not match its pixels")?;

        let mut encoded = Vec::new();
        image
            .write_to(&mut std::io::Cursor::new(&mut encoded), image::ImageFormat::Png)
            .with_context(|| format!("encoding {}", path.display()))?;

        if std::fs::read(path).is_ok_and(|existing| existing == encoded) {
            return Ok(false);
        }
        std::fs::write(path, &encoded).with_context(|| format!("writing {}", path.display()))?;
        Ok(true)
    }
}

fn mix(a: u8, b: u8, t: f32) -> u8 {
    (a as f32 + (b as f32 - a as f32) * t).round().clamp(0.0, 255.0) as u8
}

fn shade(colour: Rgb, factor: f32) -> Rgb {
    [
        (colour[0] as f32 * factor).clamp(0.0, 255.0) as u8,
        (colour[1] as f32 * factor).clamp(0.0, 255.0) as u8,
        (colour[2] as f32 * factor).clamp(0.0, 255.0) as u8,
    ]
}

/// A measurement texture: a checkerboard with a grid over it.
///
/// The checker is what makes a stretched texture obvious -- a square that is
/// not square is visible from anywhere in a room, where a stretched grid line
/// is not.
///
/// `label` is `None` for all but one of these on purpose. A world-aligned
/// projection mirrors on opposite walls -- that is what makes a corridor's two
/// sides line up, and it is not going away -- so any *text* in a tiling
/// texture reads backwards on half the surfaces in a room. On the texture
/// whose whole job is to be counted, the number is worth that. On the four
/// general-purpose ones it is just litter, sixteen times per wall.
pub fn measure(light: Rgb, dark: Rgb, label: Option<&str>) -> Canvas {
    let size = DEV_SIZE;
    let cells = DEV_SPAN / DEV_CELL; // 4
    let cell_px = (size / cells) as i32;
    let mut canvas = Canvas::new(size, size, dark);

    for cy in 0..cells as i32 {
        for cx in 0..cells as i32 {
            let colour = if (cx + cy) % 2 == 0 { light } else { dark };
            canvas.rect(cx * cell_px, cy * cell_px, (cx + 1) * cell_px, (cy + 1) * cell_px, colour);
        }
    }

    // A faint quarter-cell grid, for placing something to 4 units.
    let quarter = cell_px / 4;
    for i in 0..(size as i32 / quarter) {
        for p in 0..size as i32 {
            canvas.blend(i * quarter, p, [255, 255, 255], 0.06);
            canvas.blend(p, i * quarter, [255, 255, 255], 0.06);
        }
    }

    // Cell borders, brighter.
    for i in 0..cells as i32 {
        for p in 0..size as i32 {
            canvas.blend(i * cell_px, p, [255, 255, 255], 0.28);
            canvas.blend(p, i * cell_px, [255, 255, 255], 0.28);
        }
    }

    // The tile edge, brighter still, so a texture's own extent is readable.
    for p in 0..size as i32 {
        for edge in [0, size as i32 - 1] {
            canvas.blend(edge, p, [255, 255, 255], 0.5);
            canvas.blend(p, edge, [255, 255, 255], 0.5);
        }
    }

    // What the grid means, once per tile, on the one texture that is for
    // measuring rather than for building.
    if let Some(label) = label {
        canvas.text(label, (cell_px / 2, cell_px / 2), 2, [255, 255, 255]);
        canvas.text(
            &format!("{DEV_CELL}"),
            (cell_px * 3 + cell_px / 2, cell_px * 3 + cell_px / 2),
            2,
            [255, 255, 255],
        );
    }
    canvas
}

/// A flat colour with diagonal hatching and its own name across it.
pub fn tool(colour: Rgb, label: &str) -> Canvas {
    let size = TOOL_SIZE as i32;
    let mut canvas = Canvas::new(TOOL_SIZE, TOOL_SIZE, colour);

    // Hatching, so a tool brush is obvious even edge-on where a flat colour
    // could pass for wall.
    let dark = shade(colour, 0.72);
    for y in 0..size {
        for x in 0..size {
            if (x + y).rem_euclid(16) < 6 {
                canvas.set(x, y, dark);
            }
        }
    }

    // A border, so two abutting tool brushes are two brushes.
    for p in 0..size {
        for edge in [0, 1, size - 2, size - 1] {
            canvas.set(edge, p, shade(colour, 0.55));
            canvas.set(p, edge, shade(colour, 0.55));
        }
    }

    canvas.text(label, (size / 2, size / 2), 2, [255, 255, 255]);
    canvas
}

/// A plain colour with a subtle noise, for a surface that wants no pattern.
pub fn flat(colour: Rgb, label: Option<&str>) -> Canvas {
    let size = DEV_SIZE as i32;
    let mut canvas = Canvas::new(DEV_SIZE, DEV_SIZE, colour);
    for y in 0..size {
        for x in 0..size {
            // A cheap deterministic hash, so the same texture comes out of
            // every build byte for byte.
            let n = ((x as u32).wrapping_mul(1_664_525) ^ (y as u32).wrapping_mul(1_013_904_223))
                .wrapping_mul(2_654_435_761);
            let jitter = ((n >> 24) as f32 / 255.0 - 0.5) * 0.06;
            canvas.blend(x, y, if jitter > 0.0 { [255, 255, 255] } else { [0, 0, 0] }, jitter.abs());
        }
    }
    if let Some(label) = label {
        canvas.text(label, (size / 2, size / 2), 2, [255, 255, 255]);
    }
    canvas
}

/// A sky: a vertical gradient with a horizon line.
pub fn sky(top: Rgb, bottom: Rgb) -> Canvas {
    let size = DEV_SIZE as i32;
    let mut canvas = Canvas::new(DEV_SIZE, DEV_SIZE, top);
    for y in 0..size {
        let t = y as f32 / (size - 1) as f32;
        let colour = [mix(top[0], bottom[0], t), mix(top[1], bottom[1], t), mix(top[2], bottom[2], t)];
        for x in 0..size {
            canvas.set(x, y, colour);
        }
    }
    canvas
}

/// One texture the set contains.
pub struct DevTexture {
    /// Path under the art root, without an extension.
    pub name: &'static str,
    pub canvas: fn() -> Canvas,
    /// The material shader to write for it.
    pub shader: &'static str,
}

/// Every texture in the standard set.
///
/// A list rather than a loop over colours, because each of these means
/// something specific and the meaning belongs next to the colour.
pub fn set() -> Vec<DevTexture> {
    vec![
        // --- measurement -------------------------------------------------
        DevTexture {
            name: "dev/grid",
            shader: "lit",
            canvas: || measure([148, 152, 160], [92, 96, 104], None),
        },
        DevTexture {
            name: "dev/measure",
            shader: "lit",
            canvas: || measure([214, 122, 48], [138, 78, 32], Some("16 VU")),
        },
        DevTexture {
            name: "dev/wall",
            shader: "lit",
            canvas: || measure([120, 128, 146], [76, 82, 96], None),
        },
        DevTexture {
            name: "dev/floor",
            shader: "lit",
            canvas: || measure([112, 118, 112], [70, 76, 72], None),
        },
        DevTexture {
            name: "dev/ceiling",
            shader: "lit",
            canvas: || measure([132, 130, 122], [84, 82, 78], None),
        },
        // --- plain -------------------------------------------------------
        DevTexture { name: "dev/orange", shader: "lit", canvas: || flat([204, 112, 42], None) },
        DevTexture { name: "dev/grey", shader: "lit", canvas: || flat([128, 132, 138], None) },
        DevTexture {
            name: "dev/door",
            shader: "lit",
            canvas: || measure([170, 138, 92], [112, 90, 60], None),
        },
        DevTexture {
            name: "dev/sky_void",
            shader: "sky",
            canvas: || sky([56, 68, 96], [122, 134, 158]),
        },
        // --- tools -------------------------------------------------------
        // Colours chosen to be distinguishable from each other and from any
        // world material: nothing in `dev/` is this saturated.
        DevTexture { name: "tools/nodraw", shader: "unlit", canvas: || tool([122, 116, 96], "NODRAW") },
        DevTexture { name: "tools/clip", shader: "unlit", canvas: || tool([176, 58, 96], "CLIP") },
        DevTexture {
            name: "tools/playerclip",
            shader: "unlit",
            canvas: || tool([200, 74, 74], "PLAYER"),
        },
        DevTexture { name: "tools/npcclip", shader: "unlit", canvas: || tool([150, 62, 130], "NPC") },
        DevTexture { name: "tools/trigger", shader: "unlit", canvas: || tool([210, 118, 32], "TRIGGER") },
        DevTexture { name: "tools/hint", shader: "unlit", canvas: || tool([196, 186, 48], "HINT") },
        DevTexture { name: "tools/skip", shader: "unlit", canvas: || tool([104, 76, 176], "SKIP") },
        DevTexture { name: "tools/skybox", shader: "sky", canvas: || tool([88, 146, 196], "SKY") },
        DevTexture {
            name: "tools/blocklight",
            shader: "unlit",
            canvas: || tool([70, 90, 110], "LIGHT"),
        },
        DevTexture { name: "tools/grate", shader: "lit", canvas: || tool([110, 116, 124], "GRATE") },
        DevTexture { name: "tools/water", shader: "lit", canvas: || tool([46, 110, 138], "WATER") },
        DevTexture { name: "tools/ladder", shader: "unlit", canvas: || tool([58, 142, 104], "LADDER") },
    ]
}

/// What a run of the generator did.
#[derive(Clone, Copy, Default, Debug, PartialEq, Eq)]
pub struct Written {
    /// Files whose bytes are now different, or that did not exist.
    pub changed: usize,
    /// Files that were already exactly right.
    pub unchanged: usize,
}

impl Written {
    pub fn total(self) -> usize { self.changed + self.unchanged }
}

impl std::fmt::Display for Written {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self.changed {
            0 => write!(f, "{} already up to date", self.total()),
            n => write!(f, "{n} written, {} already up to date", self.unchanged),
        }
    }
}

/// Write the whole set as PNGs under an art root.
pub fn write_all(art_root: &Path) -> Result<Written> {
    let mut written = Written::default();
    for texture in set() {
        let path = art_root.join(format!("{}.png", texture.name));
        if (texture.canvas)().to_png(&path)? {
            written.changed += 1;
        } else {
            written.unchanged += 1;
        }
    }
    Ok(written)
}

/// Write a `.voidmat` for every texture in the set.
///
/// The set knows which shader each wants -- a sky is not lit, a tool texture
/// is not shaded -- and that is not something `batch --make-materials` can
/// work out from a PNG.
pub fn write_materials(materials_root: &Path) -> Result<Written> {
    let mut written = Written::default();
    for texture in set() {
        let path = materials_root.join(format!("{}.voidmat", texture.name));
        if let Some(parent) = path.parent() { std::fs::create_dir_all(parent)?; }
        let body = format!(
            "{}\n{{\n\t\"$basetexture\" \"{}\"\n}}\n",
            texture.shader, texture.name
        );
        if std::fs::read_to_string(&path).is_ok_and(|existing| existing == body) {
            written.unchanged += 1;
            continue;
        }
        std::fs::write(&path, body)
            .with_context(|| format!("writing {}", path.display()))?;
        written.changed += 1;
    }
    Ok(written)
}

#[cfg(test)]
mod tests;
